### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by tusx** [ComicSansMS/qr_scanner#1]
An icon for this application would be perfect. following link contain a qr code which will be perfect as icon as it is the link to this repository and thanks this application.
https://imgur.com/a/eygpIfD

**Comment by ComicSansMS** [comment]
Thanks, I added this as a logo for the project README and as an application icon. The icon doesn't really scale below 128x128, so it looks a bit scrambled up as a file icon, but I think it's still better than the system default icon.

I created a [new release](https://github.com/ComicSansMS/qr_scanner/releases/tag/1.1) with the changes.

**Comment by tusx** [comment]
@ComicSansMS  thanks for the update, much appreciated.
